### ISSUE TITLE
Systick.h and Derivative.h libraries

### ISSUE THREAD

**Issue by SnapCracklePops** [shadow85926/SimbleeArduinoCode#1]
Hello,

I'm trying to get this code to work for Simblee Lilypad but it requires Systick.h and derivative.h libraries. I don't have either of those and was wondering if you could tell me where to get them so I can run this code. 

Thank you,
Nick

**Comment by shadow85926** [comment]
The code on here is kinda borked.
biomurph fixed it, check on this
https://github.com/biomurph/SimbleeArduinoCode
